name: ci

on:
    push:
        branches:
            - main
            - beta
            - next
            - next-major
            - alpha
            - '*.*.*'

jobs:
  ci:
    env:
      PROJECT: SpecFlowElection
      SPECS_PROJECT: SpecFlowElection.Specs
    name: Build and test on ${{ matrix.os }} with dotnet ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: ['6.0.x']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - run: dotnet build $PROJECT
    - run: dotnet build $SPECS_PROJECT
    - run: dotnet test $SPECS_PROJECT
